name: www.henmao.com release
on: [push]
jobs:
  Sync-git-files:
    runs-on: ubuntu-latest
    steps:
      - name: Sync git files
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/docker/www/www.henmao.com
            git fetch --all
            git reset --hard origin/main
            git pull
